# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6431a27b00d06700d242bedcb7e50eaec9ea8ad529cf9ea00254fad8ce4161551735f5a489085d153c976e8a21e788e8cef2781c52cb26d84bcddf285bb14b3d

test:
  secret_key_base: 64d852619b50c78d12d4489104120b69911b9f0b153ac84c83cdcbf38ace466af063e33fea791e6b7fde42ae1eac706be19c17dfe5bfe6665d4406600fe6f016

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
